name: sist_hub
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_native_splash: ^2.3.1

  cupertino_icons: ^1.0.2

  flutter_bloc: ^8.1.3
  equatable: ^2.0.5
  bloc: ^8.1.2

  dartz: ^0.10.1

  shared_preferences: ^2.2.0
  flutter_secure_storage: ^8.0.0

  http: ^1.1.0
  http_parser: ^4.0.2
  fluttertoast: ^8.2.2
  photo_gallery: ^2.1.0
  permission_handler: ^10.4.3
  custom_refresh_indicator: ^2.2.1
  cached_network_image: ^3.2.3
  web_socket_channel: ^2.4.0
  # https://pub.dev/packages/info_popup try it later

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/dummy/
    - assets/images/
  #   - images/a_dot_ham.jpeg

  fonts:
    - family: Lovely_Bakery
      fonts:
        - asset: assets/fonts/Lovely_Bakery.ttf
